### ISSUE TITLE
Build error on gh pages

### ISSUE THREAD

**Issue by Emp5r0R** [nunocoracao/blowfish#2058]
Hello, I am getting this error on Git hub pages while building I don't know what caused it, out of nowhere I am getting this error. However local build is working fine 

Error:

```
WARN  Module "blowfish" is not compatible with this Hugo version: 0.87.0/0.143.1; run "hugo mod graph" for more information.
Start building sites … 
hugo v0.146.2-ff3ab192c27fccdd82393f223040874904a44e98 linux/amd64 BuildDate=2025-04-11T17:25:13Z VendorInfo=gohugoio

Total in 99 ms
Error: error building site: html/template:_shortcodes/figure.html:3:14: no such template "_internal/shortcodes/figure.html"
Error: Process completed with exit code 1.
```

**Comment by ragibson** [comment]
This is because of some breaking changes in Hugo v0.146.0 (duplicate of https://github.com/nunocoracao/blowfish/issues/2053 and https://github.com/nunocoracao/blowfish/issues/2052).

It should be fixed with https://github.com/nunocoracao/blowfish/pull/2055

**Comment by throw-a-way** [comment]
Hello, I think the error is still not resolved

Error: 
`PS D:\Personal Website Source Code\Hearth> git submodule update --remote --merge
>>
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Total 5 (delta 2), reused 5 (delta 2), pack-reused 0 (from 0)
Unpacking objects: 100% (5/5), 417 bytes | 34.00 KiB/s, done.
From https://github.com/nunocoracao/blowfish
 + 40ab5877...f8de3a33 hugo-new-version -> origin/hugo-new-version  (forced update)
PS D:\Personal Website Source Code\Hearth> hugo server
WARN  Module "blowfish" is not compatible with this Hugo version: 0.87.0/0.145.0; run "hugo mod graph" for more information.
Error: html/template:_shortcodes/figure.html:3:14: no such template "_internal/shortcodes/figure.html"`


Also this file has 9+ squiggles  Cant be good right?  \themes\blowfish\layouts\partials\head.html 

Take everything with a grain of salt i am still a noob
Thankyou

**Comment by ragibson** [comment]
Yeah, you'll have to wait for the theme author to merge the fixes in.

Their current `new-hugo-version` branch doesn't do anything other than change the version number in a config file.

**Comment by nunocoracao** [comment]
Fixed

**Comment by jayanthchandra** [comment]
Hello, 

I am still facing the same issue in the gh pages. Does the actions-hugo need to updated ?
```     - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
```
